name: "Wait for Netlify Deploy Commit"
description: "Wait for Netlify Deploy to complete for commit"
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_id:
    description: "The Netlify site id to test against"
    required: true
  max_timeout:
    description: "The max time to wait after the deployment is ready for a valid HTTP status code"
    required: false
outputs:
  url:
    description: "The fully qualified deploy URL"
runs:
  using: "node12"
  main: "index.js"
